extends:
  - standard
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  #  turn off no-unused-vars as ts plugin is broken and reports imported
  #  types as unused :rage4:
  no-unused-vars: off
  # doesn't play nicely when you need to `require(...)`
  import/first: off
