version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      # - run:
      #     name: install yarn
      #     command: npm install -g yarn
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: bootstrap
          command: NODE_ENV=development yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - run:
          command: |
            set -euxo pipefail
            if [ "$CIRCLE_BRANCH" = "master" ];
            then
              cd packages/docs
              yarn build
              # give surge.sh a nice entrypoint for urls that aren't back by
              # html files
              cp .docz/dist/index.html .docz/dist/200.html
              npx surge .docz/dist/ --domain cowtown.surge.sh
            fi
      # - run:
      #     name: release
      #     command: npm run semantic-release || true
